### ISSUE TITLE
Fails with non-7-bit chars in appendix

### ISSUE THREAD

**Issue by penma** [PierreSenellart/apxproof#27]
Using non-7-bit characters in a toappendix environment (or in a proof environment that follows a repeated theorem) writes jobname.axp with an encoding different from the input document, which means it produces "! Package inputenc Error: Invalid UTF-8 byte sequence." when the appendix is generated. This means that proofs cannot be properly typeset in non-english.

Example document attached.
[bork.txt](https://github.com/PierreSenellart/apxproof/files/2803749/bork.txt)

**Comment by PierreSenellart** [comment]
Thanks for the bug report, I can't believe I hadn't tested that. This should be fixed in the latest version in the `develop` branch. Can you try it? You can get it from https://raw.githubusercontent.com/PierreSenellart/apxproof/develop/apxproof.sty 

If this indeed solves the issue, I will release version 1.1.1 including this fix.

**Comment by penma** [comment]
Thank you for the quick reply and the fix, the updated version does indeed compile without errors and produces the output that I expected.

**Comment by PierreSenellart** [comment]
Thanks. Releasing v1.1.1.
