### ISSUE TITLE
Feature request: references to appendix sections

### ISSUE THREAD

**Issue by a3nm** [PierreSenellart/apxproof#3]
It is sometimes useful, in the appendices of a paper, to write "we do as in Appendix X", where Appendix X is the appendix created by apxproof for some section of the paper (let's call it Foo). To do this, apparently, the current way is to add at the beginning of Section Foo the following:

```
\begin{toappendix}
\label{apx:foo}
\end{toappendix}
```

Then one can write `\ref{apx:foo}`.

It would be more elegant if apxproof could automatically generate label names for the sections that it creates, ideally following the label name(s) of the current section (assuming the section has a label, and apxproof has access to it). Specifically, if Section Foo has a label "foo", it would be nice if apxproof could create the label apx:foo for the appendix automatically. (Arguably, if Foo has label "sec:foobar", the label should be "apx:foobar" and not "apx:sec:foobar".)

What do you think?

**Comment by PierreSenellart** [comment]
It would be quite difficult and dirty to implement the feature as suggested. There is no notion in LaTeX of “the label of the current section”, there can be multiple labels pointing to the current section, possibly even to different parts of the current section (with the same behavior for `\ref` but different behavior for `\pageref`). I could of course capture the first `\label` within a section, but this would really be a dirty hack.

I understand the need, however. As an alternative, I could suggest introducing commands (for instance) `\appendixref` and `appendixpageref`, without any arguments, that would print a `\ref` (resp, a `\pageref`) to the current appendix section (at least, if managed by apxproof). Would that be acceptable?

**Comment by a3nm** [comment]
In my use case, I was intending to refer to the appendix of a different section, so what you propose in your second paragraph wouldn't have been enough. (Maybe it is reasonable to have anyway, though.)

About the dirty hack, in fact, why not capture all `\label`s within a section and create corresponding labels (prefixed with "apx") to stand for the beginning of the appendix? Presumably, when the user would use the label `apx:sectionlabel` for some label of the section, all that they can want to do is `\ref{apx:sectionlabel}`, to point to the appendix of that section. So defining "apx"-prefixed copies of all labels of a section, that would go to the beginning of the corresponding appendix, doesn't sound entirely absurd to me. Maybe it's tedious/hacky to implement, though...

In practice I often use subsections in appendices anyway, so the one time I needed this and filed the issue, I ended up pointing to an appendix subsection with a manually defined label, so I guess it's also OK to decide that all of this is not worth the effort. :)

**Comment by PierreSenellart** [comment]
This makes sense, but there is a technical and usability problem with what you are suggesting: one may add a `\label{sectionlabel}` at any point of a LaTeX document. There may not be a corresponding appendix for that particular point of the document:
- either because the current section does not have a corresponding section in appendix;
- or because the appendix section has not been started yet; remember that to avoid producing empty sections in the appendix, one does not start the appendix section until its first actual content (i.e., a `toappendix`, `proof`, or `appendixproof` environment).

In both cases,  a `\ref{apx:sectionlabel}` will point to the previous appendix section, or even to the last section of the document if there is no section in the appendix yet. This is very counterintuitive. I cannot start an appendix section every time one encounters a `\label` as this would create empty sections. I cannot, either, save labels I encounter to define appendix labels whenever I create an appendix section, as nothing distinguishes in LaTeX a section label from other labels (e.g., a float label, or a theorem label).

What do you think of this?

A simple thing I could do is simply provide an `\appendixlabel` command, with `\appendixlabel{mylabel}` being a shortcut for:
```
\begin{toappendix}
\label{mylabel}
\end{toappendix}
```
This will have for effect in particular of creating a section in appendix if none already exists.

**Comment by a3nm** [comment]
On Mon, Feb 13, 2017 at 02:02:48AM -0800, Pierre Senellart wrote:
> I cannot, either, save labels I encounter to define appendix labels
> whenever I create an appendix section, as nothing distinguishes in
> LaTeX a section label from other labels (e.g., a float label, or a
> theorem label).

A very ugly solution would be to save all labels you encounter,
resetting the list when a section begins, and when you start an appendix
section create "apx"-prefixed versions of all labels encountered. As you
pointed out, this will create labels also for floats, theorems, etc.,
but they will just never get used, so they are arguably harmless (with
the "apx"-prefix avoiding any conflicts). But OK, it's not pretty.

> A simple thing I could do is simply provide an `\appendixlabel`
> command, with `\appendixlabel{mylabel}` being a shortcut for:
> ```
> \begin{toappendix}
> \label{mylabel}
> \end{toappendix}
> ```
> This will have for effect in particular of creating a section in
> appendix if none already exists.

That's also an option, but I'm not sure the conciseness win with
`\appendixlabel` relative to the 3-line block is worth the added
complexity...

So I'm not sure what I prefer, between the ugly solution above,
`\appendixlabel`, or just not doing anything.

-- 
Antoine Amarilli

**Comment by PierreSenellart** [comment]
I really dislike your ugly solution. Not only it is not pretty (and would be quite painful to implement, TeX is not particularly made to handle complex data structures), but a user who would legitimately use `apx:thm:foobar` to refer to a version of a theorem *in the appendix* (this would be a bit of a strange thing to do, but it is certainly something that a user would try) would get a non-sensical reference instead of the actual theorem number or `??`.

`\appendixlabel` does not add much complexity, it is trivial to code and add to the documentation. But yes, it is yet another command to remember.

**Comment by a3nm** [comment]
On Mon, Feb 13, 2017 at 02:19:16AM -0800, Pierre Senellart wrote:
> I really dislike your ugly solution. Not only it is not pretty (and
> would be quite painful to implement, TeX is not particularly made to
> handle complex data structures), but a user who would legitimately use
> `apx:thm:foobar` to refer to a version of a theorem *in the appendix*
> (this would be a bit of a strange thing to do, but it is certainly
> something that a user would try) would get a non-sensical reference
> instead of the actual theorem number or `??`.

In fact this is a related question: in some cases it would make sense to
point to a copy of a theorem in the appendix, or to its proof in the
appendix. So maybe labels like apx:thm:foobar should be handled
specifically for this purpose anyway, i.e., be introduced for the copy
of a theorem in the appendix -- at this point the appendix section has
started and they cannot be mistaken for a section label.

But yeah, all of this looks complicated.

> `\appendixlabel` does not add much complexity, it is trivial to code
> and add to the documentation. But yes, it is yet another command to
> remember.

OK. This depends on whether you think it's worth it or not.

Independently from this, your `\appendixref` and `\appendixpageref` may
be sensible to have too. :)

-- 
Antoine Amarilli

**Comment by PierreSenellart** [comment]
I'm closing this for now, since there is no consensus on what should be done. I may revisit this when I think about how to handle more generally hyperlinks in apxproof.
