### ISSUE TITLE
Compatibility with natbib

### ISSUE THREAD

**Issue by thefiercerabbit** [PierreSenellart/apxproof#38]
It seems that `apxproof` doesn't work well with `natbib`. Here is an example.

```LaTeX
\documentclass{article}

\usepackage[numbers]{natbib}
\usepackage{apxproof}

\begin{filecontents*}[overwrite]{refs.bib}
@article{thomas1998update,
  title={An update on the four-color theorem},
  author={Thomas, Robin},
  journal={Notices of the AMS},
  volume={45},
  number={7},
  pages={848--859},
  year={1998}
}

@article{robertson1986graph,
  title={Graph minors. II. Algorithmic aspects of tree-width},
  author={Robertson, Neil and Seymour, Paul D.},
  journal={Journal of algorithms},
  volume={7},
  number={3},
  pages={309--322},
  year={1986},
  publisher={Elsevier}
}

\end{filecontents*}


\begin{document}
  Here is a reference that is not in appendix \cite{thomas1998update}.

  \begin{toappendix}
    The same reference should be displayed here \cite{thomas1998update} since it's already been used.
    However, the following won't \cite{robertson1986graph}.
  \end{toappendix}


  \bibliographystyle{plainnat}
  \bibliography{refs}
\end{document}
```

**Comment by PierreSenellart** [comment]
Thanks for the bug report. Fixed in the latest version of the development version of apxproof (commit 2a2807), that you can download from https://raw.githubusercontent.com/PierreSenellart/apxproof/develop/apxproof.sty

natbib modifies the way citation works in quite an intrusive way, so that was not a trivial fix, and there may still be some issues.

A couple of notes:

- Always call natbib before apxproof.
- The two bibliographies use different numberings of items, and (by default) different styles to avoid confusion from the reader (but this can be changed, see documentation).
- If you use the option `bibliography=same` to have a single bibliography, no natbib-related issues are expected (in this new version or earlier versions).
